import React from "react";
import type { NextPage } from "next";
import Navbar from "../components/Navbar";
import Head from "next/head";

const about: NextPage = () => {
  return (
    <>
      <Head>
        <title>Adrián Aranda / About</title>
        <meta name="description" content="Generated by create next app" key="Adrian" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar></Navbar>
      <div className=" projects">
        <div className="flex justify-center items-center">
          <div className="flex-column w-11/12 sm:w-2/4">
            <h3 className="text-white pt-2 text-[3em] sm:text-[3.5em] transition ease-in-out duration-1000 hover:text-red-400 w-auto inline-block bg-gradient-to-r hover:-translate-y-1">
              <strong>Hello there!</strong>
            </h3>
            <p className="text-white text-justify">
              <br />
              👋 Thanks for passing by! I'm Adrian Aranda, a software engineer from Barcelona with a background in sound engineering and audiovisual/digital
              media. I'm currently part of <a href="https://www.bolt.com" className="text-indigo-300 animation-pulse transition ease-in-out duration-1000 hover:text-blue-600	">Bolt</a>'s engineering team.
              <br />
              <br />
              🙇🏻 My colleagues would say I am an social and creative engineer with great skills to see the big picture. I value innovative thinking, clear goals
              and having the chance to get involved in projects, as I am really proactive and enjoy sharing new ideas and solutions.
              <br />
              Due to having a strong audiovisual background I consider I have well-developed UX/UI instincts and I can provide a good POV when product
              designing.
              <br />
              <br />
              🖥️ As a full-stack engineer I can work in both front and back end. I especially like fintech projects and always try to surround myself with more
              experienced people whom I can learn from.
              <br />
              <br />
              ⭐️ Among my biggest passions I can highlight tech, music and chess. (I'm a multi-instrumentalist and I have my own home studio!)
            </p>
          </div>
        </div>
      </div>
    </>
  );
};

export default about;
