import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import adrianPhoto from "../public/adrianphoto.jpg";
import Navbar from "../components/Navbar";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Adrián Aranda</title>
        <meta
          name="description"
          content="Generated by create next app"
          key="Adrian"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="flex justify-around items-center">
        <div className="relative item-detail">
          <Image alt="Adrián Aranda photo" src={adrianPhoto} layout={"fill"} objectFit={"contain"} />
        </div>
        <p className="text-black w-2/5 bg-yellow-300 skew-y-12">WELCOME TO MY NICE SITE ILL TRY TO MAKE IT AS PLEASANT AS POSSIBLE SO YOU HIRE ME OKAY?</p>
      </div>
    </div>
  );
};

export default Home;
